---
- name: Update mirrorlist
  ansible.builtin.template:
    src: mirrorlist
    dest: /etc/pacman.d/mirrorlist
    backup: false
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Update pacman configuration file
  ansible.builtin.template:
    src: pacman.conf
    dest: /etc/pacman.conf
    backup: false
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Upgrade system
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: true

- name: Install offical repos packages
  community.general.pacman:
    name: "{{ packages.official_repos }}"
    state: present
  become: true

- name: Install microcode (AMD)
  community.general.pacman:
    name:
      - amd-ucode
  become: true
  when: "'AuthenticAMD' in ansible_processor"

- name: Install microcode (Intel)
  community.general.pacman:
    name:
      - intel-ucode
  become: true
  when: "'GenuineIntel' in ansible_processor"

- name: Detect GPU
  ansible.builtin.shell: set -o pipefail && lspci | grep -i 'VGA\|3D\|display' # noqa command-instead-of-shell
  register: gpu_result
  changed_when: false

- name: Install GPU drivers (AMD)
  community.general.pacman:
    name:
      - mesa
      - mesa-utils
      # https://wiki.archlinux.org/title/Xorg
      - xf86-video-amdgpu
      # https://wiki.archlinux.org/title/Hardware_video_acceleration
      - mesa-vdpau
      - libva-mesa-driver
      # https://wiki.archlinux.org/title/Vulkan
      - vulkan-radeon
      # https://wiki.archlinux.org/title/GPGPU
      - rocm-hip-runtime
      - rocm-hip-sdk
      - hip-runtime-amd
      - rocm-core
      - rocm-opencl-runtime
      - rocm-opencl-sdk
    state: present
  become: true
  when: ("'radeon' in gpu_result.stdout.lower()") or ("'amd/ati' in gpu_result.stdout.lower()")

- name: Install GPU drivers (Intel)
  community.general.pacman:
    name:
      - mesa
      - mesa-utils
      # https://wiki.archlinux.org/title/Xorg
      - xf86-video-intel
      # https://wiki.archlinux.org/title/Hardware_video_acceleration
      - intel-media-driver
      - libva-intel-driver
      # https://wiki.archlinux.org/title/Vulkan
      - vulkan-intel
      # https://wiki.archlinux.org/title/GPGPU
      - intel-compute-runtime
      - opencl-clover-mesa
    state: present
  become: true
  when: "'intel' in gpu_result.stdout.lower()"

- name: Install GPU drivers (Nvidia)
  community.general.pacman:
    name:
      - mesa
      - mesa-utils
      # https://wiki.archlinux.org/title/Xorg
      - nvidia
      # https://wiki.archlinux.org/title/Hardware_video_acceleration
      - nvidia-utils
      # https://wiki.archlinux.org/title/GPGPU
      - cuda
      - opencl-nvidia
    state: present
  become: true
  when: "'nvidia' in gpu_result.stdout.lower()"
