---
- name: "Ensure group \"{{ item }}\" exists"
  become: true
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ [user.group] + user.groups }}"

- name: "Ensure user \"{{ user.username }}\" exists with correct config"
  become: true
  ansible.builtin.user:
    name: "{{ user.username }}"
    group: "{{ user.group }}"
    shell: "{{ user.shell }}"
    groups: "{{ user.groups }}"

# HACK: not the cleanest solution
- name: "Set password for user {{ user.username }}"
  no_log: true
  become: true
  ansible.builtin.shell: > # noqa command-instead-of-shell
    set -o pipefail && echo {{ user_password | b64encode }} | base64 -d | passwd {{ user.username }} -s

- name: Allow wheel group to sudo
  become: true
  community.general.sudoers:
    name: group-wheel
    nopassword: false
    state: present
    group: wheel
    commands: ALL
