---
name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
          ansible-galaxy install -r requirements.yml

      - name: Lint
        run: |
          ansible --version
          ansible-lint --version
          yamllint --version
          yamllint --format parsable .
          ansible-lint -v
