---
- name: Git config user.name
  become: true
  become_user: "{{ user.username }}"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git.name }}"

- name: Git config user.email
  become: true
  become_user: "{{ user.username }}"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git.email_b64 | b64decode }}"

