---
- name: Set authorized key taken from file
  become: true
  become_user: "{{ user.username }}"
  ansible.posix.authorized_key:
    user: "{{ user.username }}"
    state: present
    key: "{{ lookup('file', '/home/' + user.username + '/.ssh/id_ed25519.pub') }}"

- name: Git config user.name
  become: true
  become_user: "{{ user.username }}"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git.name }}"

- name: Git config user.email
  become: true
  become_user: "{{ user.username }}"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git.email_b64 | b64decode }}"

- name: "Copy home foldes with owner and permissions" # noqa risky-file-permissions
  become: true
  become_user: "{{ user.username }}"
  ansible.builtin.copy:
    src: "resources/home/{{ item }}/"
    dest: "/home/{{ user.username }}/{{ item }}"
    owner: "{{ user.username }}"
    group: "{{ user.group }}"
  loop:
    - .config
    - .local

- name: Copy .zshrc with owner and permissions
  become: true
  become_user: "{{ user.username }}"
  ansible.builtin.copy:
    src: resources/home/.zshrc
    dest: "/home/{{ user.username }}/.zshrc"
    mode: "0660"
    owner: "{{ user.username }}"
    group: "{{ user.group }}"
