---
- name: Setup plymouth
  ansible.builtin.import_tasks: plymouth.yml

- name: Setup sshd
  ansible.builtin.import_tasks: sshd.yml

- name: Build initramfs
  ansible.builtin.import_tasks: mkinitcpio.yml

- name: Setup systemd units
  ansible.builtin.import_tasks: systemd.yml
