---
- name: Copy sshd_config config
  ansible.builtin.copy:
    src: resources/system/etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    mode: "0644"
    remote_src: true
    owner: root
    group: root
  become: true
